---
- hosts: localhost
  tasks:
    - name: Integration testing
      command: cat /etc/ansible/hosts
      register: a
    - debug:
        var: a.stdout_lines
    - name: testing
      command: cat /root/aws-vpc
      register: b
    - debug:
        var: b.stdout_lines
